### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by Splaktar** [angular/devkit#172]
I’m trying to debug and work with schematics in angular/devkit, especially after yesterday's merges, I wasn’t able to find any developer docs for devkit. Just running the builds in `package.json` is giving me errors. Here's the output from `npm run build`:
```
rror: Circular dependency detected between the following packages: rxjs
    at _getHashOf (/Users/splaktar/Git/angular/devkit/lib/packages.ts:37:15)
    at pkg.dependencies.forEach.depName (/Users/splaktar/Git/angular/devkit/lib/packages.ts:29:46)
    at Array.forEach (native)
    at _getHashOf (/Users/splaktar/Git/angular/devkit/lib/packages.ts:28:26)
    at Object.<anonymous> (/Users/splaktar/Git/angular/devkit/lib/packages.ts:155:38)
    at Module._compile (module.js:570:32)
    at Object.require.extensions..ts (/Users/splaktar/Git/angular/devkit/lib/bootstrap-local.js:79:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/splaktar/Git/angular/devkit/lib/bootstrap-local.js:99:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/splaktar/Git/angular/devkit/bin/devkit-admin:16:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Do I need to have Bazel installed as well as the npm dependencies?
Are there Bazel build commands that I need to run?

Do I need to be on NPM 5? I'm currently running Node 6.11.0 and NPM 3.10.10.

**Comment by hansl** [comment]
Hi,

`_getHashOf` should not try to reach rxjs. That looks like a bug that's easy to fix and might improve actually. Let me check locally.

**Comment by hansl** [comment]
> Do I need to have Bazel installed as well as the npm dependencies?

Not for building locally.

> Do I need to be on NPM 5? I'm currently running Node 6.11.0 and NPM 3.10.10.

Our CI is running on Node 6.11, so that should be covered too.

Please note that you only need to run `npm link` and you can use the local `schematics` tool.

**Comment by Splaktar** [comment]
I tried with a fresh NVM environment using Node 8.0.0 and NPM 5.4.2 and I see the same error when running `npm run build` or `devkit-admin build` after doing `npm i` and `npm link` in `devkit/`.

**Comment by hansl** [comment]
Seriously cannot reproduce this here on my Mac (or Linux) machines. What's your system?

**Comment by Splaktar** [comment]
OS X El Capitan.
I also have the angular-cli project `npm link'd`.

**Comment by hansl** [comment]
Let's chat on gitter. It might be easier.

**Comment by Splaktar** [comment]
```
@angular/cli: local (v1.5.0-beta.1, branch: master)
node: 8.0.0
os: darwin x64
@ngtools/json-schema: 1.1.0
typescript: 2.3.4
```
```
@angular/cli: local (v1.5.0-beta.1, branch: master)
node: 6.11.0
os: darwin x64
@ngtools/json-schema: 1.1.0
typescript: 2.3.4
```

**Comment by hansl** [comment]
After talking offline with @Splaktar we discovered his repo was compromised with node_modules everywhere. This has now been fixed, but I'm adding preinstall steps to prevent this to happen in the future.

**Comment by Splaktar** [comment]
Yep, don't run `npm i` down in `devkit/packages/angular_devkit/schematics`. It only needs to be run in the root.

Thanks much @hansl!

**Comment by Splaktar** [comment]
Would it be worth my time to send a PR with some markdown similar to https://github.com/angular/angular-cli#development-hints-for-working-on-angular-cli that applies to devkit? Would it be in the README.md or another `.md` file?
