### ISSUE TITLE
Cannot use collection outside node_modules

### ISSUE THREAD

**Issue by sasxa** [angular/devkit#241]
### Bug Report or Feature Request (mark with an `x`)
```
- [?] bug report -> please search issues before submitting
- [?] feature request
```
Cannot use collection outside `node_modules`.

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

```
Angular CLI: 1.5.0-rc.2
Node: 8.5.0
OS: win32 x64
Angular: 5.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server
... platform-webworker, platform-webworker-dynamic, router
... service-worker

@angular/cli: 1.5.0-rc.2
@angular-devkit/build-optimizer: 0.0.29
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.2
@schematics/angular: 0.0.48
@schematics/schematics: 0.0.3
typescript: 2.5.3
webpack: 3.8.1
```

### Repro steps

I made `<root>/.test/` folder and copied `<root>/node_modules/@schematics/angular` into it.
I get an error below when I run:

    ng g e ooo --collection .test/angular -d

### The log given by the failure

```
C:\dev\projects\sch-test>ng g e ooo --collection .test/angular -d
Could not find module ".test/angular" from "C:\\dev\\projects\\sch-test".
Error: Could not find module ".test/angular" from "C:\\dev\\projects\\sch-test".
    at Object.resolve (C:\dev\projects\sch-test\node_modules\@angular-devkit\core\node\resolve.js:140:11)
    at NodeModulesEngineHost._resolvePackageJson (C:\dev\projects\sch-test\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:22:21)
    at NodeModulesEngineHost._resolveCollectionPath (C:\dev\projects\sch-test\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:43:36)
    at NodeModulesEngineHost.createCollectionDescription (C:\dev\projects\sch-test\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:94:27)
    at SchematicEngine.createCollection (C:\dev\projects\sch-test\node_modules\@angular-devkit\schematics\src\engine\engine.js:47:40)
    at Object.getCollection (C:\dev\projects\sch-test\node_modules\@angular\cli\utilities\schematics.js:37:31)
    at Class.run (C:\dev\projects\sch-test\node_modules\@angular\cli\tasks\schematic-get-options.js:11:41)
    at Class.beforeRun (C:\dev\projects\sch-test\node_modules\@angular\cli\commands\generate.js:90:31)
    at Promise.resolve.then (C:\dev\projects\sch-test\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:138:24)
    at <anonymous>

```

### Desired functionality

If I move schematics files to `<root>/node_modules/.test/angular` it works:
```
C:\dev\projects\sch-test>ng g e ooo --collection .test/angular -d
  create src/app/ooo.enum.ts (20 bytes)

NOTE: Run with "dry run" no changes were made.
```
**Is it possible to use collections from outside `node_modules` ?**

I'd like to keep my custom collections in my git repo, among other things.

### Mention any other details that might be useful

I believe the problem is in [`angular_devkit/schematics/tools/node-module-engine-host.ts`](https://github.com/angular/devkit/blob/26f78ab33dec373b4cc6a2c6e05ecd20f4f71843/packages/angular_devkit/schematics/tools/node-module-engine-host.ts#L31-L62), but can't figure out exactly what it is...

**Comment by hansl** [comment]
Hi @sasxa ,

Have you tried `./.test/angular` instead?

We recommend to use the `schematics` command line instead of the Angular CLI for now, when testing the schematics locally. The CLI is recommended for e2e tests and when using schematics.

**Comment by sasxa** [comment]
@hansl Thanks, it's working with relative path:

    schematics ./.test/angular:enum --name ooo --dry-run
    ng g e ooo --collection ./.test/angular -d
