### ISSUE TITLE
Using recent installs, (command line) schematics: command not found

### ISSUE THREAD

**Issue by paisanousa** [angular/devkit#387]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```
  [X ] **Prepared to submit Pull Request following confirmation of finding**

### Area
```
- [X ] devkit -----> cause:  incorrect path to recently split-out schematic-cli
- [ ] schematics --> symptom:  (command line) schematics: command not found
```

### Versions

```
$ node -v
v9.3.0
$ npm -v
5.6.0
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

### Repro steps

```
Beginning list of global installs:
$ npm list --depth=0 -g
/home/dennis/.nvm/versions/node/v9.3.0/lib
├── @angular/cli@1.6.3
└── npm@5.6.0
```

```
Globally install group of recent compatibles: 
  npm i -g @angular-devkit/core@0.0.24
  npm i -g @angular-devkit/schematics@0.0.43
  npm i -g @schematics/schematics@0.0.12
  npm i -g rxjs@5.5.6

Installation details:
$ npm i -g @angular-devkit/core@0.0.24
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@angular-devkit/core/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular-devkit/core@0.0.24
added 65 packages in 15.412s

$ npm i -g @angular-devkit/schematics@0.0.43
npm WARN @angular-devkit/schematics@0.0.43 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@angular-devkit/schematics/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular-devkit/schematics@0.0.43
added 67 packages in 9.466s

$ npm i -g @schematics/schematics@0.0.12
npm WARN @schematics/schematics@0.0.12 requires a peer of @angular-devkit/core@0.0.24 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/schematics@0.0.12 requires a peer of @angular-devkit/schematics@0.0.43 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/schematics@0.0.12 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.

+ @schematics/schematics@0.0.12
added 1 package in 1.752s

$ npm i -g rxjs@5.5.6
+ rxjs@5.5.6
added 2 packages in 4.003s
```

```
Resulting list of global installs:
$ npm list --depth=0 -g
/home/dennis/.nvm/versions/node/v9.3.0/lib
├── @angular-devkit/core@0.0.24
├── @angular-devkit/schematics@0.0.43
├── @angular/cli@1.6.3
├── @schematics/schematics@0.0.12
├── npm@5.6.0
└── rxjs@5.5.6
```

```
Run schematics from command line, fails:
$ schematics
schematics: command not found

Attempt to verify schematics, fails:
$ which schematics
 
(nothing is found)
```

**The cause of this issue is illuminated when the devkit repo is 
cloned, linked, and schematics is run from the command line:**
```
Beginning list of global installs:
$ npm list --depth=0 -g/home/dennis/.nvm/versions/node/v9.3.0/lib
├── @angular/cli@1.6.3
└── npm@5.6.0

Clone:
$ git clone git@github.com:angular/devkit.git
Cloning into 'devkit'...
remote: Counting objects: 5987, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 5987 (delta 22), reused 37 (delta 21), pack-reused 5934
Receiving objects: 100% (5987/5987), 1.26 MiB | 4.11 MiB/s, done.
Resolving deltas: 100% (3673/3673), done.

Change directory:
$ cd devkit/

Verify git status:
devkit (master)$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

Install dependencies:
devkit (master)$ npm i

> v8-profiler@5.7.0 preinstall /home/dennis/devkit/node_modules/v8-profiler
> node -e 'process.exit(0)'
...
(skip details of successful install)
...
make: Leaving directory '/home/dennis/devkit/node_modules/v8-profiler/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 884 packages in 64.892s

Link folder:
devkit (master)$ npm link
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 10.603s
/home/dennis/.nvm/versions/node/v9.3.0/bin/build-optimizer -> /home/dennis/.nvm/versions/node/v9.3.0/lib/node_modules/@angular-devkit/devkit/bin/build-optimizer
/home/dennis/.nvm/versions/node/v9.3.0/bin/devkit-admin -> /home/dennis/.nvm/versions/node/v9.3.0/lib/node_modules/@angular-devkit/devkit/bin/devkit-admin
/home/dennis/.nvm/versions/node/v9.3.0/bin/purify -> /home/dennis/.nvm/versions/node/v9.3.0/lib/node_modules/@angular-devkit/devkit/bin/purify
/home/dennis/.nvm/versions/node/v9.3.0/bin/schematics -> /home/dennis/.nvm/versions/node/v9.3.0/lib/node_modules/@angular-devkit/devkit/bin/schematics
/home/dennis/.nvm/versions/node/v9.3.0/lib/node_modules/@angular-devkit/devkit -> /home/dennis/devkit

Verify link:
devkit (master)$ npm list --depth=0 -g
/home/dennis/.nvm/versions/node/v9.3.0/lib
├── @angular-devkit/devkit@0.0.0 -> /home/dennis/devkit
├── @angular/cli@1.6.3
└── npm@5.6.0

Verify schematics:
devkit (master)$ which schematics 
/home/dennis/.nvm/versions/node/v9.3.0/bin/schematics

Run schematics from command line:
devkit (master)$ schematics 
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:602:3)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

### The log given by the failure

```
(see above)
```

### Desired functionality

**Expect behavior exhibited prior to schematics-cli split-out (commit: c89beff):**
```
Install globally, group of compatible packages prior to split-out:
  npm i -g @angular-devkit/core@0.0.22
  npm i -g @angular-devkit/schematics@0.0.42
  npm i -g @schematics/schematics@0.0.11
  npm i -g rxjs@5.5.6

  
Resulting list of global installs:
$ npm list --depth=0 -g
/home/dennis/.nvm/versions/node/v9.3.0/lib
├── @angular-devkit/core@0.0.22
├── @angular-devkit/schematics@0.0.42
├── @angular/cli@1.6.3
├── @schematics/schematics@0.0.11
├── npm@5.6.0
└── rxjs@5.5.6


Verify schematics:
$ which schematics 
/home/dennis/.nvm/versions/node/v9.3.0/bin/schematics

Run schematics from command line:
$ schematics
schematics [CollectionName:]SchematicName [options, ...]

By default, if the collection name is not specified, use the internal collection provided
by the Schematics CLI.

Options:
    --debug             Debug mode. This is true by default if the collection is a relative
                        path (in that case, turn off with --debug=false).
    --dry-run           Do not output anything, but instead just show what actions would be
                        performed. Default to true if debug is also true.
    --force             Force overwriting files that would otherwise be an error.
    --list-schematics   List all schematics from the collection, by name.
    --verbose           Show more information.

    --help              Show this message.

Any additional option is passed to the Schematics depending on
```
### Mention any other details that might be useful

The issue is caused by line 14 of /devkit/bin/schematics which currently is...

    require(packages['@angular-devkit/schematics'].bin['schematics']);
    
It should be...

    require(packages['@angular-devkit/schematics-cli'].bin['schematics']);

    
**If a review confirms these results, I am prepared to submit a pull request to resolve.**

**Comment by thibaultsavary** [comment]
I can confirm this behavior.
Awesome issue report @paisanousa

**Comment by paisanousa** [comment]
@clydin pull request (#389) commit (7723d4d) fixes this issue.
Thanks @thibaultsavary 
Thanks @clydin

**Comment by filipesilva** [comment]
Closing as fixed as per @paisanousa's comment.
