### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by Kamshak** [angular/devkit#39]
Hey, i'd love to play around with this a bit but i can't get it to work. When trying to yarn link the CLI i always end up with 

```
Error: Cannot find module '../src/cli'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@_/schematics-cli/bin/schematics.js:9:1)
```

**Comment by hansl** [comment]
Are you trying to `link` the directory directly? You need to link the root package.json. It will install the proper CLI as well.

**Comment by Kamshak** [comment]
That worked, thanks! Didn't occur to me to just link the entire directory :see_no_evil:
