### ISSUE TITLE
schematics-cli on linux fails to create a new semantics project

### ISSUE THREAD

**Issue by douglasward** [angular/devkit#464]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

### Versions
```
node: v6.9.4
npm: v5.6.0
linux: ubuntu 16.04
```

### Repro steps

run:
```
$ schematics  blank --name=my-component
```

### The log given by the failure
```bash
CREATE /my-component/README.md (635 bytes)
CREATE /my-component/.gitignore (191 bytes)
CREATE /my-component/package.json (535 bytes)
CREATE /my-component/src/collection.json (231 bytes)
CREATE /my-component/tsconfig.json (631 bytes)
CREATE /my-component/src/my-component/index.ts (317 bytes)
CREATE /my-component/src/my-component/index_spec.ts (474 bytes)
npm ERR! file /tmp/my-component/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token , in JSON at position 3 while parsing near '123,10,32,32,34,110,97,...'
npm ERR! File: /tmp/my-component/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

### Desired functionality
The blank schematics folder should be created with the expected content.

### Mention any other details that might be useful

All of the files in the folder include contents such as `123,10,32,32,34,110,97`.

Downgrading to `~0.3.2` fixes the problem.

Might be the same problem as https://github.com/angular/devkit/issues/453, if so I apologise, and please feel free to close.

**Comment by johnhny** [comment]
Got the exact same issue (all files with contents such as `123,10,32,32,34,110,97`...) on RHEL 7 / npm 5.3 / node 6.11.4 .
Downgrade from 0.4.3 to 0.4.2/0.4.1/0.4.0 does not resolve the issue.... 
0.3.2 seems to work 👍 

Any workarounds to get it working with >=0.4.0 ?

**Comment by nmorado** [comment]
same here:

OS: win32 x64
Node: 6.11.4
Schematics: 0.4.5

**Comment by FriOne** [comment]
I get another error on macos

> /Users/myuser/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/util/subscribeTo.js:42
>         throw new TypeError(msg);
>         ^
> 
> TypeError: You provided 'function reduceOperatorFunction(source) {
>         return pipe_1.pipe(scan_1.scan(function (acc, value, index) {
>             return accumulator(acc, value, index + 1);
>         }), takeLast_1.takeLast(1))(source);
>     }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
>     at Object.exports.subscribeTo (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/util/subscribeTo.js:42:15)
>     at Object.subscribeToResult (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:26)
>     at MergeMapSubscriber._innerSub (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
>     at MergeMapSubscriber._tryNext (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
>     at MergeMapSubscriber._next (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
>     at MergeMapSubscriber.notifyComplete (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:148:18)
>     at InnerSubscriber._complete (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/InnerSubscriber.js:37:21)
>     at InnerSubscriber.Subscriber.complete (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:128:18)
>     at Observable.rxjs_1.concat.rxjs_1.concat.rxjs_1.Observable.obs [as _subscribe] (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js:113:17)
>     at Observable.subscribe (/Users/lyubiroman/.nvm/versions/node/v8.11.1/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Observable.js:162:69)

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12144
