### ISSUE TITLE
Build errors - Cannot read property 'match' of undefined - virtual-fs/path.js:178

### ISSUE THREAD

**Issue by Mathem8tic** [angular/devkit#658]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Angular CLI: 6.0.0-rc.2
Node: 9.10.1
OS: linux x64
Angular: 6.0.0-rc.3
... animations, bazel, common, compiler, compiler-cli, core
... forms, http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker, upgrade

@angular/cli: 6.0.0-rc.2
@angular-devkit/architect: 0.5.4
@angular-devkit/build-angular: 0.5.4
@angular-devkit/build-optimizer: 0.5.4
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: 0.5.4
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.2.4
@schematics/angular: 0.5.4
@schematics/update: 0.5.4
typescript: 2.7.2
webpack: 4.5.0

### Repro steps

ng serve --prod

### The log given by the failure

ng serve --prod

/home/fitmylife/Code/tester/node_modules/@angular-devkit/core/src/virtual-fs/path.js:178
    if (path.match(/^[A-Z]:[\/\\]/)) {
             ^

TypeError: Cannot read property 'match' of undefined
    at Object.normalize (/home/fitmylife/Code/tester/node_modules/@angular-devkit/core/src/virtual-fs/path.js:178:14)
    at options.fileReplacements.forEach (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/src/browser/index.js:99:55)
    at Array.forEach (<anonymous>)
    at BrowserBuilder.buildWebpackConfig (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/src/browser/index.js:98:34)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:36:50)
    at Observable.subscribe (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Observable.js:162:69)
    at /home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/home/fitmylife/Code/tester/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/map.js:92:26)

### Mention any other details that might be useful

I ran the migration to test if that would fix issue, noticed a path that is seemingly incorrect in the angular.json...

"configurations": {
..
"production": {
..
 "fileReplacements": [
                {
                  "from": "src/environments/environment.ts",
                  "to": "dist/undefined" <---generated path...
                }
              ]

**Comment by Mathem8tic** [comment]
Also noticing that there is a second '/' in the paths after node_modules of the log. This seems likely to be root of issue...

/home/fitmylife/Code/tester/node_modules//src/virtual-fs/path.js:178

**Comment by Mathem8tic** [comment]
Installed fresh everything, used global CLI to create new project, seems to work.  Not sure what the cause of issue is but I will close since its likely caused by bad configuration at some point by me.  Worth noting that the project was working prior to rc3.
