### ISSUE TITLE
User errors shouldn't print stack traces

### ISSUE THREAD

**Issue by dansanderson** [angular/devkit#8]
When the CLI is reporting an error that represents invalid options or inputs, it should not print a stack trace. It should still return a shell status code.

Some schematics are throwing an Error for these messages, but we need to differentiate between user errors and internal tool errors to hide diagnostic info in the first case (unless, perhaps, a --debug tool flag is included).

**Comment by paisanousa** [comment]
The following specifically identifies where some of these stack traces are appearing:

### schematics command-line errors cluttered with stack traces


### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Versions

```
:~$ node -v
v9.4.0

:~$ npm -v
5.6.0

Globals:
:~$ npm list --depth=0 -g
/home/dennis/.nvm/versions/node/v9.4.0/lib
├── @angular-devkit/core@0.0.28
├── @angular-devkit/schematics@0.0.51
├── @angular-devkit/schematics-cli@0.0.8
└── npm@5.6.0

:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

### Repro steps


* Step 1 - Verify "schematics" available at command line:

```
:~$ schematics
schematics [CollectionName:]SchematicName [options, ...]

By default, if the collection name is not specified, use the internal collection provided
by the Schematics CLI.

Options:
    --debug             Debug mode. This is true by default if the collection is a relative
                        path (in that case, turn off with --debug=false).
    --dry-run           Do not output anything, but instead just show what actions would be
                        performed. Default to true if debug is also true.
    --force             Force overwriting files that would otherwise be an error.
    --list-schematics   List all schematics from the collection, by name.
    --verbose           Show more information.

    --help              Show this message.

Any additional option is passed to the Schematics depending on
```

* Step 2 - Verify properly-formatted command creates new schematic:

```
:~$ schematics @schematics/schematics:schematic --name demo
CREATE /demo/README.md (635 bytes)
CREATE /demo/.gitignore (191 bytes)
CREATE /demo/package.json (523 bytes)
CREATE /demo/src/collection.json (1698 bytes)
CREATE /demo/src/my-full-schematic/index.ts (2455 bytes)
CREATE /demo/src/my-full-schematic/index_spec.ts (864 bytes)
CREATE /demo/src/my-full-schematic/schema.json (306 bytes)
CREATE /demo/src/my-other-schematic/index.ts (1346 bytes)
CREATE /demo/src/my-other-schematic/index_spec.ts (509 bytes)
CREATE /demo/src/my-schematic/index.ts (1458 bytes)
CREATE /demo/src/my-schematic/index_spec.ts (482 bytes)
CREATE /demo/tsconfig.json (631 bytes)
CREATE /demo/src/my-full-schematic/files/test2 (127 bytes)
CREATE /demo/src/my-full-schematic/files/test__INDEX__ (29 bytes)
```

* Step 3 - Mangle "schematics" command to create error conditions:

```
Create various "not found" conditions to observe error output:
:~$ schematics @schemMANGLE/schematics:schematic --name demo
:~$ schematics @schematics/schemMANGLE:schematic --name demo
:~$ schematics @schematics/schematics:schemMANGLE --name demo

Each command fails as expected. However, the error messages include 
stack traces which might lead one to believe the CLI has failed rather 
than properly reporting user errors. The output of the three attempts 
is recorded in the next section.
```

### The log given by the failure


```
:~$ schematics @schemMANGLE/schematics:schematic --name demo
Error while running script "/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts":
Error: Could not find module "@schemMANGLE/schematics" from "/home/dennis/devkit_projects/sbox".
    at Object.resolve (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/core/node/resolve.ts:140:11)
    at NodeModulesEngineHost._resolvePackageJson (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:22:21)
    at NodeModulesEngineHost._resolveCollectionPath (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:43:36)
    at NodeModulesEngineHost.createCollectionDescription (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:102:27)
    at SchematicEngine.createCollection (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/engine.ts:46:40)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts:96:27)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..ts (/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:83:14)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:87
    throw err;
    ^

Error: Could not find module "@schemMANGLE/schematics" from "/home/dennis/devkit_projects/sbox".
    at Object.resolve (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/core/node/resolve.ts:140:11)
    at NodeModulesEngineHost._resolvePackageJson (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:22:21)
    at NodeModulesEngineHost._resolveCollectionPath (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:43:36)
    at NodeModulesEngineHost.createCollectionDescription (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:102:27)
    at SchematicEngine.createCollection (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/engine.ts:46:40)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts:96:27)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..ts (/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:83:14)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

```
:~$ schematics @schematics/schemMANGLE:schematic --name demo
Error while running script "/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts":
Error: Could not find module "@schematics/schemMANGLE" from "/home/dennis/devkit_projects/sbox".
    at Object.resolve (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/core/node/resolve.ts:140:11)
    at NodeModulesEngineHost._resolvePackageJson (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:22:21)
    at NodeModulesEngineHost._resolveCollectionPath (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:43:36)
    at NodeModulesEngineHost.createCollectionDescription (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:102:27)
    at SchematicEngine.createCollection (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/engine.ts:46:40)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts:96:27)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..ts (/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:83:14)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:87
    throw err;
    ^

Error: Could not find module "@schematics/schemMANGLE" from "/home/dennis/devkit_projects/sbox".
    at Object.resolve (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/core/node/resolve.ts:140:11)
    at NodeModulesEngineHost._resolvePackageJson (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:22:21)
    at NodeModulesEngineHost._resolveCollectionPath (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:43:36)
    at NodeModulesEngineHost.createCollectionDescription (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:102:27)
    at SchematicEngine.createCollection (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/engine.ts:46:40)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts:96:27)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..ts (/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:83:14)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

```
:~$ schematics @schematics/schematics:schemMANGLE --name demo
Error while running script "/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts":
Error: Schematic "schemMANGLE" not found in collection "@schematics/schematics".
    at NodeModulesEngineHost.createSchematicDescription (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:134:19)
    at SchematicEngine.createSchematic (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/engine.ts:81:40)
    at CollectionImpl.createSchematic (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/collection.ts:11:29)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts:109:30)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..ts (/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:83:14)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:87
    throw err;
    ^

Error: Schematic "schemMANGLE" not found in collection "@schematics/schematics".
    at NodeModulesEngineHost.createSchematicDescription (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:134:19)
    at SchematicEngine.createSchematic (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/engine.ts:81:40)
    at CollectionImpl.createSchematic (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics/src/engine/collection.ts:11:29)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/packages/angular_devkit/schematics_cli/bin/schematics.ts:109:30)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..ts (/home/dennis/devkit_contrib/devkit/lib/bootstrap-local.js:83:14)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dennis/devkit_contrib/devkit/bin/schematics:14:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

### Desired functionality


The expected results would be concise error messages with no stack traces. The messages might include information pointing the user to the correct command format and/or usage:

```
Similar to this error message: 
:~$ schematics @schematics/schematics:schematic --namMANGLE demo
Schematic input does not validate against the Schema: {}
Errors:
   should have required property 'name'
 ```

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12165
