### ISSUE TITLE
Uncaught ReferenceError: sourceMapSupport is not defined after upgrading to Angular 6

### ISSUE THREAD

**Issue by vdespa** [angular/devkit#918]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] help needed
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
node v9.4.0
npm 5.6.0
Windows 10 or MacOS.

### Repro steps
I have upgraded an Angular 5.2 application from 5.2 to 6 following the guide at https://update.angular.io/ 

While trying **ng test**, I get the error "sourceMapSupport is not defined".  

### The log given by the failure
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) ERROR
  {
    "message": "Uncaught ReferenceError: sourceMapSupport is not defined\nat http://localhost:9877node_modules/karma-source-map-support/lib/client.js:1:1\n\nReferenceError: sourceMapSupport is not defined\n    at http://localhost:9877node_modules/karma-source-map-support/lib/client.js:1:1",
    "str": "Uncaught ReferenceError: sourceMapSupport is not defined\nat http://localhost:9877node_modules/karma-source-map-support/lib/client.js:1:1\n\nReferenceError: sourceMapSupport is not defined\n    at http://localhost:9877node_modules/karma-source-map-support/lib/client.js:1:1"
  }

### Desired functionality
Tests run without problems.

### Mention any other details that might be useful
I cannot figure out what is can cause this error. If anybody has an idea on how to debug this, I would be grateful.

I do not think it is a bug in devkit but the error itself is unclear what the cause can be.

**Comment by vdespa** [comment]
After deleting yarn.lock it worked again.
